"""update movie model

Revision ID: 18d87c6a4654
Revises: 86f349e6627b
Create Date: 2020-03-13 09:47:27.742042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d87c6a4654'
down_revision = '86f349e6627b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('cover', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'cover')
    # ### end Alembic commands ###
