"""add movie table

Revision ID: 86f349e6627b
Revises: c1d85844eb72
Create Date: 2020-03-12 20:57:55.301022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f349e6627b'
down_revision = 'c1d85844eb72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('imdb_title', sa.String(length=512), nullable=True),
    sa.Column('catalogue_entry', sa.String(length=64), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    # ### end Alembic commands ###
